"""
EigenCV Valid ID Manifest Generator
=====================================
Scans all active database JSON files and generates a flat, human- and 
AI-readable VALID_IDS.md file listing every valid ID in the database.

Include this file in your cloud AI upload so the AI can select IDs 
from a simple list instead of parsing complex nested JSON structures.

Usage:
    python tools/generate_id_manifest.py
    -> Writes VALID_IDS.md to the repository root
"""
import os
import json
from datetime import datetime

def load_json_safe(path):
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"[WARNING] Could not read {path}: {e}")
        return {}

def generate_manifest(root_dir=None):
    if root_dir is None:
        root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    db_dir = os.path.join(root_dir, 'cv', 'database', 'active')
    output_path = os.path.join(root_dir, 'VALID_IDS.md')

    lines = [
        "# EigenCV — Valid ID Manifest",
        f"<!-- Auto-generated by tools/generate_id_manifest.py on {datetime.now().strftime('%Y-%m-%d %H:%M')} -->",
        "",
        "> **AI INSTRUCTION:** When writing `build_config.json`, you MUST only use IDs",
        "> listed in this file. Do not invent or guess IDs. If an ID is not here, it does not exist.",
        "",
    ]

    # --- Experience ---
    exp_path = os.path.join(db_dir, 'experience.json')
    exp_db = load_json_safe(exp_path)
    if exp_db:
        lines += ["## EXPERIENCE", ""]
        for company_id, company_data in exp_db.items():
            company_name = company_data.get('company', company_id)
            lines.append(f"### `{company_id}` — {company_name}")
            bullets = company_data.get('bullets', {})
            if bullets:
                lines.append("Available bullet IDs:")
                for bullet_id in bullets.keys():
                    text_preview = str(bullets[bullet_id])[:80].replace('\n', ' ')
                    lines.append(f"  - `{bullet_id}` → _{text_preview}..._")
            lines.append("")

    # --- Projects ---
    proj_path = os.path.join(db_dir, 'projects.json')
    proj_db = load_json_safe(proj_path)
    if proj_db:
        lines += ["## PROJECTS", ""]
        lines.append("Available project IDs:")
        for proj_id, proj_data in proj_db.items():
            name = proj_data.get('name', proj_id) if isinstance(proj_data, dict) else proj_id
            lines.append(f"  - `{proj_id}` — {name}")
        lines.append("")

    # --- Education ---
    edu_path = os.path.join(db_dir, 'education.json')
    edu_db = load_json_safe(edu_path)
    if edu_db:
        lines += ["## EDUCATION", ""]
        lines.append("Available education IDs:")
        for edu_id, edu_data in edu_db.items():
            degree = edu_data.get('degree', edu_id) if isinstance(edu_data, dict) else edu_id
            lines.append(f"  - `{edu_id}` — {degree}")
        lines.append("")

    # --- Extracurriculars ---
    extra_path = os.path.join(db_dir, 'extracurriculars.json')
    extra_db = load_json_safe(extra_path)
    if extra_db:
        lines += ["## EXTRACURRICULARS", ""]
        lines.append("Available extracurricular IDs:")
        for extra_id, extra_data in extra_db.items():
            title = extra_data.get('title', extra_id) if isinstance(extra_data, dict) else extra_id
            lines.append(f"  - `{extra_id}` — {title}")
        lines.append("")

    # --- Languages ---
    lang_path = os.path.join(db_dir, 'languages.json')
    lang_db = load_json_safe(lang_path)
    if lang_db:
        lines += ["## LANGUAGES", ""]
        lines.append("Available language IDs:")
        for lang_id, lang_data in lang_db.items():
            name = lang_data.get('language', lang_id) if isinstance(lang_data, dict) else lang_id
            lines.append(f"  - `{lang_id}` — {name}")
        lines.append("")

    lines += [
        "---",
        "",
        "> Generated from `cv/database/active/`. Re-run `python tools/generate_id_manifest.py`",
        "> after updating your database to keep this file current.",
    ]

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"[OK] VALID_IDS.md written to: {output_path}")
    return output_path

if __name__ == "__main__":
    generate_manifest()
